### ISSUE TITLE
Environment configuration maxiconda not working

### ISSUE THREAD

**Issue by awinia-github** [Semi-ATE/maxiconda#29]
Steps to reproduce:

1.  Download and install: https://github.com/Semi-ATE/maxiconda/releases/latest/download/maxiconda.exe
2. After installation the following command failed: **mamba create -n myenv python=3.7 maxiconda**
3. The error message looks as follows:
![image](https://user-images.githubusercontent.com/60256982/153893303-563b15dc-2af1-403b-a821-68c1a0db8a96.png)

**Comment by nerohmot** [comment]
Ok, you are mixing Anaconda and Maxiconda ... that will not work !
I can see so, because the first 6 channels mentioned are from Anaconda !

You need to uninstall Anaconda (add or remove programs), then go to your home directory and make sure all renascences of Anaconda (like `.condarc` ) are gone.

Then also remove your current installaction of Maxiconda (just remove it from your home directory with `rm -rf`).

Then install Maxiconda again like in the [video](https://www.youtube.com/watch?v=bE5yMQbvlY8).

As prove it does work here is what happens when I do `mamba create -n myenv python=3.7 maxiconda` :

![image](https://user-images.githubusercontent.com/3516972/153982726-2f2a9ab5-f6e3-48da-be1c-85264f5eefac.png)
...

Note that there should **ONLY** be 4 channels : 2 for conda-forge (arch & noarch) and 2 for Semi-ATE (arch and noarch) 😉

**Comment by nerohmot** [comment]
Please close this issue when it works for you!

**Comment by awinia-github** [comment]
Your have been right. There was some `.condarc` file in my home folder. I changed it from:

```
channels:
  - Semi-ATE
  - defaults
  - conda-forge
channel_priority: strict
auto_activate_base: false
```

into:

```
channels:
  - Semi-ATE
  - conda-forge
channel_priority: strict
auto_activate_base: false
```

After this I was able to create the _myenv_ environment as described in the video.
